### ISSUE TITLE
🧱🐜: The School of Bitcoin Roadmap (#beat1plan)

### ISSUE THREAD

**Issue by trainfarb** [hu3agency/LP0_polymathProcess#40]
### EP0_beatDrop_The School of Bitcoin's Goal: MVP Curriculum
Notes from (1/28) Kieran email: 
MVP (now): Reddit Style Lightning site using beatDrops as curriculum proposals. Top ten beatDrops/curriculum proposals are "consensus". beatDrop/curriculum proposal is a way for people to bundle the content they want to see in classes and on exams for the community. Give people flexibility into which curriculums they use based on which really resonate with them. Meant to be free flowing way for people to propose curriculum items without needed to be locked into NFTs or tracked on a blockchain.

Stacks (later): Stacks will be what we use for exams. Issue STX tokens that can be used to upgrade the exams rather than the curriculums. Exams created based on the different curriculums that are defined as consensus (above).

**Roadmap**
- [ ] #1
- [ ] Present beatDrop/curriculum Proposal Flow to the team
- [ ] Receive curriculum proposals from different team members
- [ ] Discuss thoughts on filling out the proposals with the team
