### ISSUE TITLE
🧱🐜: Roadmap for My EF (#beat1plan)

### ISSUE THREAD

**Issue by trainfarb** [hu3agency/LP0_polymathProcess#41]
### EP0_beatDrop_My Father's House Goal: Launch NFT Series
**Roadmap**
- [ ] 12/29: Upload Repositories
  - [ ] Delete Hashlips Files that aren't needed
  - [ ] Change & Document all variable names for each file
  - [ ] Document how everything is pushed up to GitHub
- [ ] Create Art Series for Each Character
- [ ] Upload Art Series to IPFS for Each Character
- [ ] Create Smart Contract for Each Character
- [ ] Add Smart Contract to Minting dApp for Each Character
- [ ] Deploy dApp for Each Character
- [ ] Define/Share Public Roadmap
- [ ] Create Content Strategy
- [ ] Support Hashlips Community
  - [ ] Create pull request to add in files created by E&F (like the icons for iPhone etc.)
  - [ ] Offer to create a collaborative wiki repository on GitHub (Created by EF, Griot, & hu3)
  - [ ] Create private sale for community
